version: '3.8'

services:
  bitor:
    image: ghcr.io/bitorscanner/bitor:latest
    restart: unless-stopped
    environment:
      - API_ENCRYPTION_KEY=${API_ENCRYPTION_KEY:?API encryption key is required}
    volumes:
      - ./data:/app/pb_data
      - ./nuclei-templates:/app/nuclei-templates
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bitor.rule=Host(`${DOMAIN:-localhost}`)"
      - "traefik.http.routers.bitor.entrypoints=websecure"
      - "traefik.http.routers.bitor.tls=true"
      - "traefik.http.routers.bitor.tls.certresolver=letsencrypt"
      - "traefik.http.services.bitor.loadbalancer.server.port=8090"
    networks:
      - bitor-net

  traefik:
    image: traefik:v2.10
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/acme.json:/acme.json
      - ./traefik/traefik.yml:/traefik.yml:ro
    networks:
      - bitor-net
    depends_on:
      - bitor

networks:
  bitor-net:
    driver: bridge 