name = "bitor-frontend"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[build]
command = "cd frontend && pnpm install && pnpm build"
watch_dir = "frontend"

[site]
bucket = "frontend/build"

[env.production]
name = "bitor-frontend-prod"

[env.staging]
name = "bitor-frontend-staging" 