name: Deploy Backend to Railway

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build Go binary
        run: |
          cd backend
          go mod download
          go build -o bitor main.go

      - name: Build Frontend for Backend
        run: |
          cd frontend
          pnpm install --frozen-lockfile
          pnpm build
          mkdir -p ../backend/pb_public
          cp -r build/* ../backend/pb_public/

      - name: Test Backend Build with Frontend
        run: |
          cd backend
          go build -o bitor main.go

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ Backend build test passed! Ready for manual deployment to Railway.'
            }) 